// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PirateTARpe23.Data;

#nullable disable

namespace PirateTARpe23.Data.Migrations
{
    [DbContext(typeof(PirateTARpe23Context))]
    [Migration("20241115093513_goku")]
    partial class goku
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PirateTARpe23.Core.Domain.FileToDatabase", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PirateID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.ToTable("FilesToDatabase");
                });

            modelBuilder.Entity("PirateTARpe23.Core.Domain.Pirate", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Health")
                        .HasColumnType("float");

                    b.Property<double>("HungerLevel")
                        .HasColumnType("float");

                    b.Property<string>("Item")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrimaryWeapon")
                        .HasColumnType("int");

                    b.Property<int>("SecondaryWeapon")
                        .HasColumnType("int");

                    b.Property<int>("StatusEffect")
                        .HasColumnType("int");

                    b.Property<double>("ThirstLevel")
                        .HasColumnType("float");

                    b.Property<double>("XP")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.ToTable("Pirates");
                });
#pragma warning restore 612, 618
        }
    }
}
